// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VestBooks.Data;

#nullable disable

namespace VestBooks.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONÁRIO"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("perfil_regra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_regra", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("usuario_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usuario_perfil", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "1",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "1",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("usuario_token", (string)null);
                });

            modelBuilder.Entity("VestBooks.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("AutorId");

                    b.ToTable("autor");

                    b.HasData(
                        new
                        {
                            AutorId = 1,
                            Nome = "Jorge Amado"
                        },
                        new
                        {
                            AutorId = 2,
                            Nome = "Machado de Assis"
                        },
                        new
                        {
                            AutorId = 3,
                            Nome = "Manuel Bandeira"
                        },
                        new
                        {
                            AutorId = 4,
                            Nome = "João Guimarães Rosa"
                        },
                        new
                        {
                            AutorId = 5,
                            Nome = "José de Alencar"
                        },
                        new
                        {
                            AutorId = 6,
                            Nome = "Luís de Camões"
                        },
                        new
                        {
                            AutorId = 7,
                            Nome = "Carolina Maria de Jesus"
                        },
                        new
                        {
                            AutorId = 8,
                            Nome = "Carlos drummond de Andrade"
                        },
                        new
                        {
                            AutorId = 9,
                            Nome = "Darcy Ribeiro"
                        },
                        new
                        {
                            AutorId = 10,
                            Nome = "Graciliano Ramos"
                        },
                        new
                        {
                            AutorId = 11,
                            Nome = "Aluísio Azevedo"
                        },
                        new
                        {
                            AutorId = 12,
                            Nome = "José Paulo Paes"
                        },
                        new
                        {
                            AutorId = 13,
                            Nome = "Conceição Evaristo"
                        },
                        new
                        {
                            AutorId = 14,
                            Nome = "Ailton Krenak"
                        },
                        new
                        {
                            AutorId = 15,
                            Nome = "Lima Barreto"
                        },
                        new
                        {
                            AutorId = 16,
                            Nome = "Chimamanda Ngozi Adichie"
                        },
                        new
                        {
                            AutorId = 17,
                            Nome = "Caio Fernando Abreu"
                        },
                        new
                        {
                            AutorId = 18,
                            Nome = "Cartola"
                        },
                        new
                        {
                            AutorId = 19,
                            Nome = "Lewis Carroll"
                        },
                        new
                        {
                            AutorId = 20,
                            Nome = "Djamilia Pereira de Almdeida"
                        },
                        new
                        {
                            AutorId = 21,
                            Nome = "Lygia Fagundes Telles"
                        },
                        new
                        {
                            AutorId = 22,
                            Nome = "Paulina Chiziane"
                        },
                        new
                        {
                            AutorId = 23,
                            Nome = "Rachel de Queiroz"
                        },
                        new
                        {
                            AutorId = 24,
                            Nome = "Conceição Evaristo"
                        },
                        new
                        {
                            AutorId = 25,
                            Nome = "Julia Lopes de Almeida"
                        },
                        new
                        {
                            AutorId = 26,
                            Nome = "Narcisa Amália"
                        },
                        new
                        {
                            AutorId = 27,
                            Nome = "Sophia de Mello Breyner Andresen"
                        },
                        new
                        {
                            AutorId = 28,
                            Nome = "Nísia Floresta"
                        });
                });

            modelBuilder.Entity("VestBooks.Models.Faculdade", b =>
                {
                    b.Property<int>("FaculdadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FaculdadeId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            FaculdadeId = 1,
                            Nome = "ENEM"
                        },
                        new
                        {
                            FaculdadeId = 2,
                            Nome = "UNICAMP"
                        },
                        new
                        {
                            FaculdadeId = 3,
                            Nome = "FUVEST"
                        });
                });

            modelBuilder.Entity("VestBooks.Models.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Avaliacao")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FaculdadeId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Publicacao")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("LivroId");

                    b.HasIndex("AutorId");

                    b.HasIndex("FaculdadeId");

                    b.ToTable("livro");

                    b.HasData(
                        new
                        {
                            LivroId = 1,
                            AutorId = 1,
                            Avaliacao = "4",
                            Descricao = "A narrativa explora a paixão de Dona Flor por seus dois maridos, mostrando como ela lida com as diferenças entre eles e como busca a felicidade em meio a um triângulo amoroso.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Dona Flor e seus dois maridos.png",
                            Nome = "Dona flor e seus dois maridos",
                            Publicacao = "1966"
                        },
                        new
                        {
                            LivroId = 2,
                            AutorId = 2,
                            Avaliacao = "4,8",
                            Descricao = "é um romance de Machado de Assis que conta a história de Bento Santiago, um homem que, já velho, decide escrever um livro para narrar sua versão dos acontecimentos de sua juventude.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Dom Casmurro.png",
                            Nome = "Dom Casmurro",
                            Publicacao = "1899"
                        },
                        new
                        {
                            LivroId = 3,
                            AutorId = 1,
                            Avaliacao = "4,8",
                            Descricao = "A história se passa em Salvador, Bahia, e retrata a vida de um grupo de meninos de rua que vivem em um trapiche abandonado, enfrentam a miséria, a violência e sobrevivem roubando e praticando pequenos crimes, mas também demonstram um forte senso de união e solidariedade.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Capitães De Areia .png",
                            Nome = "Capitães da Areia",
                            Publicacao = "1937"
                        },
                        new
                        {
                            LivroId = 4,
                            AutorId = 3,
                            Avaliacao = "4,7",
                            Descricao = "é um livro de poemas que reúne todos os livros de poesia do autor, desde o seu primeiro, A Cinza das Horas, até os poemas que escreveu ao longo de sua vida.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Estrelas Da Vida Inteira.png",
                            Nome = "Estrela da vida inteira",
                            Publicacao = "1965"
                        },
                        new
                        {
                            LivroId = 5,
                            AutorId = 4,
                            Avaliacao = "4,9",
                            Descricao = "conta a história de amor entre Riobaldo e Diadorim (ou Reinaldo). O ex-jagunço Riobaldo relata, para um interlocutor não nomeado na obra, fatos de sua juventude em meio a um bando de jagunços.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Grande Sertão Veredas.png",
                            Nome = "Grande Sertão: Veredas",
                            Publicacao = "1956 "
                        },
                        new
                        {
                            LivroId = 6,
                            AutorId = 1,
                            Avaliacao = "4,8",
                            Descricao = "A obra narra o caso de amor entre o árabe Nacib e a sertaneja Gabriela, como pano de fundo o período áureo do cacau na região de Ilhéus, descrevendo as alterações profundas da vida social da Bahia da década de 1920.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Gabriela,cravo e canela.png",
                            Nome = "Gabriela Cravo e Canela",
                            Publicacao = "1958"
                        },
                        new
                        {
                            LivroId = 7,
                            AutorId = 5,
                            Avaliacao = "4,6",
                            Descricao = "O romance conta o amor de um branco, Martim Soares Moreno, pela índia Iracema, a virgem dos lábios de mel. A relação do casal serviria de alegoria para a formação da nação brasileira. A índia Iracema representaria a natureza virgem e a inocência enquanto o colonizador Martim representa a cultura (europeia).",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/iracema.png",
                            Nome = "Iracema",
                            Publicacao = "1865"
                        },
                        new
                        {
                            LivroId = 8,
                            AutorId = 2,
                            Avaliacao = "4,8",
                            Descricao = "Brás Cubas decide narrar sua própria vida após a morte. A narrativa começa com sua agonia e enterro, e retrocede para sua infância, juventude e vida adulta. O livro é uma crítica à sociedade da época, com seus costumes, valores e hipocrisias.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Memórias Póstumas de Brás Cubas.png",
                            Nome = "Memórias Póstumas de Brás Cubas",
                            Publicacao = "1880"
                        },
                        new
                        {
                            LivroId = 9,
                            AutorId = 6,
                            Avaliacao = "4,7",
                            Descricao = "Os sonetos de Camões abordam uma variedade de temas, com destaque para o amor, a paixão, a saudade, a melancolia, a fé e a reflexão sobre a vida e a morte. Sua poesia é um retrato da alma humana, com suas alegrias, tristezas, esperanças e desilusões.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Sonetos De Camões.png",
                            Nome = "Sonetos",
                            Publicacao = "1595"
                        },
                        new
                        {
                            LivroId = 10,
                            AutorId = 7,
                            Avaliacao = "4,9",
                            Descricao = "O livro é um diário em que Carolina Maria de Jesus narra seu cotidiano, descrevendo as dificuldades que enfrenta como mãe solteira de três filhos, trabalhando como catadora de papel e enfrentando a falta de recursos para suprir as necessidades básicas da família.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Quarto De Despejo.png",
                            Nome = "Quarto de Despejo",
                            Publicacao = "1960"
                        },
                        new
                        {
                            LivroId = 11,
                            AutorId = 8,
                            Avaliacao = "3,8",
                            Descricao = "O momento em que o país vivia a Era Vargas é a mais cobrada no ENEM. Isso acontece porque ela reflete o engajamento social e político do poeta, características que costumam ser muito bem aproveitadas",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Poesia Completa Carlos Drummond De Andrade.png",
                            Nome = "Poesia Completa",
                            Publicacao = ""
                        },
                        new
                        {
                            LivroId = 12,
                            AutorId = 9,
                            Avaliacao = "4,9",
                            Descricao = "A obra busca responder à pergunta: quem são os brasileiros? mergulhando na história do Brasil, analisando as matrizes culturais, os mecanismos de formação étnica e cultural, os conflitos e as contradições.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/O Povo Brasileiro.png",
                            Nome = "O povo brasileiro",
                            Publicacao = "1995"
                        },
                        new
                        {
                            LivroId = 13,
                            AutorId = 10,
                            Avaliacao = "4,8",
                            Descricao = "A história acompanha a saga de Fabiano, Sinhá Vitória e seus dois filhos, além da cachorra Baleia, em busca de melhores condições de vida. A família enfrenta a seca, a fome, a violência e a injustiça social, sendo constantemente humilhada e explorada pelos proprietários de terra.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/Vidas Secas.png",
                            Nome = "Vidas Secas",
                            Publicacao = "1938"
                        },
                        new
                        {
                            LivroId = 14,
                            AutorId = 11,
                            Avaliacao = "4,7",
                            Descricao = "O Cortiço é um romance naturalista que retrata a vida de pessoas pobres que viviam em cortiços no Rio de Janeiro no final do século XIX. O livro denuncia a exploração e as péssimas condições de vida dos moradores.",
                            Destaque = true,
                            FaculdadeId = 1,
                            Foto = "/img/livros/o cortiço.png",
                            Nome = "O Cortiço",
                            Publicacao = "1890"
                        },
                        new
                        {
                            LivroId = 15,
                            AutorId = 12,
                            Avaliacao = "4,8",
                            Descricao = "é um livro composto por: Prosas: Vinte textos em prosa poética que abordam temas diversos marcados pela concisão, pela ironia e pelo humor, e Odes Mínimas: Treze poemas curtos, concisos e minimalistas, que exploram os temas das prosas,com uma linguagem depurada e essencial. Os poemas são marcados pela reflexão, pela ironia e pela brevidade.",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Prosas seguidas de odes mínimas.png",
                            Nome = "Prosas seguidas de odes mínimas",
                            Publicacao = "1992"
                        },
                        new
                        {
                            LivroId = 16,
                            AutorId = 13,
                            Avaliacao = "4,8",
                            Descricao = "Olhos d'água é um livro de contos da escritora Conceição Evaristo que aborda a vida de pessoas negras e afro-brasileiras.A metáfora dos olhos d'água simboliza a união estabelecida entre passado, presente e futuro",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Olhos d'água.png",
                            Nome = "Olhos d’água",
                            Publicacao = "2014"
                        },
                        new
                        {
                            LivroId = 17,
                            AutorId = 14,
                            Avaliacao = "4,8",
                            Descricao = "é um livro que questiona o sistema capitalista, o consumismo e a destruição ambiental. Composto por cinco textos: Não se come dinheiro, Sonhos para adiar o fim do mundo, A máquina de fazer coisas, O amanhã não está à venda, A vida não é útil.",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/A vida não é útil.png",
                            Nome = "A vida não é útil",
                            Publicacao = "2020"
                        },
                        new
                        {
                            LivroId = 18,
                            AutorId = 2,
                            Avaliacao = "4,6",
                            Descricao = "Casa Velha é um romance de Machado de Assis que aborda temas como o poder das normas sociais, a ascensão social e as relações de poder entre as classes sociais",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Casa Velha.png",
                            Nome = "Casa Velha",
                            Publicacao = "1886"
                        },
                        new
                        {
                            LivroId = 19,
                            AutorId = 15,
                            Avaliacao = "4,5",
                            Descricao = "Vida e morte de M.J Gonzaga de Sá é um livro que conta a história de um jornalista negro que vive no Rio de Janeiro no início do século XX, o qual aborda temas como: Desigualdade social, Racismo, Corrupção política, Abandono das populações periféricas, Burocratização do Estado.",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Vida e morte de M.J Gonzaga de Sá.png",
                            Nome = "Vida e morte de M.J Gonzaga de Sá",
                            Publicacao = "1919"
                        },
                        new
                        {
                            LivroId = 20,
                            AutorId = 16,
                            Avaliacao = "4,2",
                            Descricao = "No seu pescoço é um livro que aborda temas  sobre injustiça social, desigualdade de gênero, sonho, nostalgia, racismo e preconceito contra imigrantes de forma combativa, sem ser abusiva",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/No seu pescoço.png",
                            Nome = "No Seu Pescoço",
                            Publicacao = "2017"
                        },
                        new
                        {
                            LivroId = 21,
                            AutorId = 17,
                            Avaliacao = "4,6",
                            Descricao = "Morangos Mofados é um livro de contos que retratam a angústia, a solidão, a repressão e a busca por liberdade de jovens na década de 1970, durante a ditadura militar no Brasil.",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Morangos mofados.png",
                            Nome = "Morangos mofados",
                            Publicacao = "1982"
                        },
                        new
                        {
                            LivroId = 22,
                            AutorId = 18,
                            Descricao = "As canções escolhidas de Cartola são Alvorada, As rosas não falam, Cordas de aço, Disfarça e chora, O inverno do meu tempo, O mundo é um moinho, Que é feito de você?, Sala de recepção, Silêncio de um cipreste e Sim",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Canções Escolhida - Cartola.png",
                            Nome = "Canções Escolhidas",
                            Publicacao = ""
                        },
                        new
                        {
                            LivroId = 23,
                            AutorId = 19,
                            Avaliacao = "4,8",
                            Descricao = "é uma história sobre uma menina que sonha que cai numa toca de coelho e acaba num mundo mágico. Lá, ela vive aventuras e se depara com o absurdo, o impossível e questiona tudo o que aprendeu até ali",
                            Destaque = true,
                            FaculdadeId = 2,
                            Foto = "/img/livros/Alice no país das maravilhas.png",
                            Nome = "Alice no país das maravilhas",
                            Publicacao = "1865 "
                        },
                        new
                        {
                            LivroId = 24,
                            AutorId = 20,
                            Avaliacao = "3,5",
                            Descricao = "A obra conta a história de Celestino, homem cujo passado de brutalidade e violência assombrosas é substituído, no crepúsculo da vida, por um amor delicado e cuidadoso pelas plantas de seu jardim.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/A visão das plantas.png",
                            Nome = "A visão das plantas",
                            Publicacao = "2019"
                        },
                        new
                        {
                            LivroId = 25,
                            AutorId = 21,
                            Avaliacao = "4,2",
                            Descricao = "O livro acompanha a jornada de três jovens mulheres universitárias no início da década de 70. Lorena, Ana Clara e Lia são de mundos distantes, vivendo impasses, cada qual com seu próprio drama durante o período turbulento da ditadura.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/As meninas.png",
                            Nome = "As meninas",
                            Publicacao = "1973"
                        },
                        new
                        {
                            LivroId = 26,
                            AutorId = 22,
                            Avaliacao = "4",
                            Descricao = "A obra conta a história de amor entre Sarnau e Mwando, na qual faz uma crítica à poligamia e às tradições machistas e patriarcais que afetam a vida das mulheres.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/Balada de amor ao vento.png",
                            Nome = "Balada de amor ao vento",
                            Publicacao = "1990"
                        },
                        new
                        {
                            LivroId = 27,
                            AutorId = 23,
                            Avaliacao = "3,5",
                            Descricao = "Na Fortaleza dos anos 1930, durante a Era Vargas, Roberto tem a missão de recrutar operários para uma nova célula de esquerda. Uma das pessoas que se interessam é Noemi: mãe de Guri e casada com um homem que não ama mais, ela está em busca de algo que a faça se sentir viva.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/Caminho de Pedras.png",
                            Nome = "Caminho de pedras",
                            Publicacao = "1937"
                        },
                        new
                        {
                            LivroId = 28,
                            AutorId = 24,
                            Avaliacao = "4,2",
                            Descricao = "A obra questiona o patriarcado e as construções sociais da masculinidade, é um retrato de um homem através dos relacionamentos que ele coleciona com várias mulheres negras.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/Canção para Ninar Menino grande.png",
                            Nome = "Canção para ninar menino grande",
                            Publicacao = "2018"
                        },
                        new
                        {
                            LivroId = 29,
                            AutorId = 25,
                            Avaliacao = "3,5",
                            Descricao = "A obra narra a história de uma jovem chamada Marta, que viveu no Rio de Janeiro no final do século XIX, é uma autobiografia ficcional que retrata as dificuldades enfrentadas por Marta e sua mãe, viúva.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/Memórias de Martha.png",
                            Nome = "Memórias de Martha",
                            Publicacao = "1899"
                        },
                        new
                        {
                            LivroId = 30,
                            AutorId = 26,
                            Avaliacao = "3",
                            Descricao = "Seus poemas revelam uma voz lírica única, que aborda temas íntimos, femininos e ligados à natureza, ao mesmo tempo em que expressam uma preocupação social evidente, especialmente em relação à abolição da escravatura, uma questão presente na sociedade brasileira do século XIX.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/Nebulosas.png",
                            Nome = "Nebulosas",
                            Publicacao = "2024"
                        },
                        new
                        {
                            LivroId = 31,
                            AutorId = 27,
                            Avaliacao = "3,7",
                            Descricao = "O livro é composto por uma série de poemas que contam a história de uma lenda sobre o assassinato de um cigano e a construção de uma imagem de Cristo.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/O cristo cigano.png",
                            Nome = "O cristo cigano",
                            Publicacao = "1961"
                        },
                        new
                        {
                            LivroId = 32,
                            AutorId = 28,
                            Avaliacao = "3,6",
                            Descricao = "A obra traça a evolução das condições femininas e mostram a experiência da autora tanto em leitura, quanto em vivências em suas viagens.",
                            Destaque = true,
                            FaculdadeId = 3,
                            Foto = "/img/livros/Opúsculo Humanitário.png",
                            Nome = "Opúsculo Humanitário",
                            Publicacao = "1853"
                        });
                });

            modelBuilder.Entity("VestBooks.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e19a59b6-c470-4bd7-ae67-25a1a09b78da",
                            DataNascimento = new DateTime(1981, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gallojunior@gmail.com",
                            EmailConfirmed = true,
                            Foto = "/img/usuarios/ddf093a6-6cb5-4ff7-9a64-83da34aee005.png",
                            LockoutEnabled = true,
                            Nome = "José Antonio Gallo Junior",
                            NormalizedEmail = "GALLOJUNIOR@GMAIL.COM",
                            NormalizedUserName = "GALLOJUNIOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEGUolcLTwPJpa5fnfVNMXAKu0aEWlQJ9uFRNcrTB4y6h2dhi5Sx7Glm88ZlDQGIFhg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3ed336cf-69d8-448b-8e3e-22ab9797bae2",
                            TwoFactorEnabled = false,
                            UserName = "GalloJunior"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VestBooks.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VestBooks.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestBooks.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VestBooks.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VestBooks.Models.Livro", b =>
                {
                    b.HasOne("VestBooks.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VestBooks.Models.Faculdade", "Faculdade")
                        .WithMany()
                        .HasForeignKey("FaculdadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Faculdade");
                });
#pragma warning restore 612, 618
        }
    }
}
